import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
  const translations = {
    en: {
      'nav.home': 'Home',
      'nav.search': 'Search',
      'nav.notifications': 'Notifications',
      'nav.messages': 'Messages',
      'nav.profile': 'Profile',
      'nav.community': 'Community',
      'nav.settings': 'Settings',
      'nav.admin': 'Admin',
      'nav.creator': 'Creator',
      'settings.title': 'Settings',
      'settings.profile': 'Profile',
      'settings.privacy': 'Privacy',
      'settings.notifications': 'Notifications',
      'settings.security': 'Security',
      'settings.appearance': 'Appearance',
      'settings.language': 'Language',
      'settings.help': 'Help',
      'settings.logout': 'Logout',
      'settings.language.title': 'Language Settings',
      'settings.language.description': 'Choose your preferred language for the site',
      'settings.language.english': 'English',
      'settings.language.japanese': 'Japanese',
      'settings.language.current': 'Current Language',
      'settings.language.success': 'Language changed successfully!',
      'settings.save': 'Save',
      'settings.cancel': 'Cancel',
      'common.loading': 'Loading...',
      'common.success': 'Success',
      'messages.languageChanged': 'Language changed successfully!',
      'messages.selectOption': 'Please select an option',
      'dashboard.followers': 'Followers',
      'dashboard.following': 'Following',
      'info.title': 'Information',
      'info.languageChange': 'Changing the language will immediately display the entire site in the new language.',
      'admin.dashboard.title': 'Admin Dashboard',
      'admin.dashboard.subtitle': 'Platform management and moderation',
      'admin.overview': 'Overview',
      'admin.users': 'User Management',
      'admin.posts': 'Post Management',
      'admin.reports': 'Report Management',
      'admin.totalUsers': 'Total Users',
      'admin.totalPosts': 'Total Posts',
      'admin.totalReports': 'Reports',
      'admin.bannedUsers': 'Banned Users',
      'admin.removedPosts': 'Removed Posts',
      'admin.user': 'User',
      'admin.role': 'Role',
      'admin.status': 'Status',
      'admin.joined': 'Joined',
      'admin.action': 'Action',
      'admin.ban': 'Ban',
      'admin.unban': 'Unban',
      'admin.manager': 'Manager',
      'admin.creator': 'Creator',
      'admin.fan': 'Fan',
      'admin.active': 'Active',
      'admin.banned': 'Banned',
      'creator.dashboard.title': 'Creator Dashboard',
      'creator.dashboard.subtitle': 'Content management and fan connections',
      'creator.overview': 'Overview',
      'creator.posts': 'Post Management',
      'creator.analytics': 'Analytics',
      'creator.fans': 'Fan Management',
      'creator.subscriptions': 'Subscriptions',
      'creator.settings': 'Settings',
      'creator.settings.title': 'Creator Settings',
      'creator.settings.subtitle': 'Customize your creator experience',
      'creator.settings.contentSettings': 'Content Settings',
      'creator.settings.monetization': 'Monetization',
      'creator.settings.profileSettings': 'Profile Settings',
      'creator.settings.edit': 'Edit',
      'creator.settings.profilePicture': 'Profile Picture',
      'creator.settings.uploadNewPicture': 'Upload a new profile picture',
      'creator.newPost': 'New Post',
      'creator.followers': 'Followers',
      'creator.totalViews': 'Total Views',
      'creator.totalLikes': 'Total Likes',
      'creator.totalEarnings': 'Total Earnings',
      'creator.postManagement': 'Post Management',
      'creator.postManagementDesc': 'Post management features will be displayed here',
      'creator.analyticsDesc': 'Analytics data will be displayed here',
      'creator.fanManagement': 'Fan Management',
      'creator.fanManagementDesc': 'Fan management features will be displayed here',
      'creator.subscriptionsDesc': 'Subscription management will be displayed here',
      'creator.settingsDesc': 'Settings screen will be displayed here',
      'creator.dashboard.newPost': 'New Post',
      'creator.dashboard.totalFollowers': 'Total Followers',
      'creator.dashboard.totalViews': 'Total Views',
      'creator.dashboard.totalLikes': 'Total Likes',
      'creator.dashboard.totalEarnings': 'Total Earnings',
      'creator.dashboard.thisMonth': 'This month',
      'creator.dashboard.quickActions': 'Quick Actions',
      'creator.dashboard.recentActivity': 'Recent Activity',
      'creator.dashboard.upcomingEvents': 'Upcoming Events',
      'creator.dashboard.performanceSummary': 'Performance Summary',
      'creator.dashboard.viewAll': 'View all',
      'creator.dashboard.viewDetailedAnalytics': 'View detailed analytics',
      'creator.dashboard.totalPosts': 'Total Posts',
      'creator.dashboard.totalComments': 'Total Comments',
      'creator.dashboard.engagementRate': 'Engagement Rate',
      'creator.quickActions.myFeed': 'My Feed',
      'creator.quickActions.myFeedDesc': 'Manage and track your content performance',
      'creator.quickActions.notifications': 'Notifications',
      'creator.quickActions.notificationsDesc': 'Stay updated with your fan interactions',
      'creator.quickActions.messages': 'Messages',
      'creator.quickActions.messagesDesc': 'Connect with your fans directly',
      'creator.quickActions.statistics': 'Statistics',
      'creator.quickActions.statisticsDesc': 'Track your performance and growth',
      'creator.quickActions.myFans': 'My Fans',
      'creator.quickActions.myFansDesc': 'Manage and interact with your fan community',
      'creator.quickActions.marketing': 'Marketing',
      'creator.quickActions.marketingDesc': 'Promote your content and grow your audience',
      'creator.quickActions.contentQueue': 'Content Queue',
      'creator.quickActions.contentQueueDesc': 'Manage your scheduled and draft posts',
      'creator.quickActions.settings': 'Settings',
      'creator.quickActions.settingsDesc': 'Customize your creator experience',
      'creator.activity.newFollower': 'started following you',
      'creator.activity.newLikes': 'Your post received 15 new likes',
      'creator.activity.newComment': 'commented on your post',
      'creator.activity.newEarnings': 'You earned ¥500 from tips',
      'creator.events.behindScenes': 'Behind the Scenes Post',
      'creator.events.fanQA': 'Fan Q&A Session',
      'creator.events.premiumContent': 'Premium Content Release',
      'creator.events.scheduledFor': 'Scheduled for',
      'creator.events.tomorrow': 'tomorrow',
      'creator.events.friday': 'Friday',
      'creator.events.sunday': 'Sunday',
      'creator.time.hoursAgo': 'hours ago',
      'creator.time.daysAgo': 'days ago',
      // Creator Feed
      'creator.feed.title': 'My Feed',
      'creator.feed.subtitle': 'Manage and track your content performance',
      'creator.feed.createPost': 'Create New Post',
      'creator.feed.allPosts': 'All Posts',
      'creator.feed.draft': 'Draft',
      'creator.feed.published': 'Published',
      'creator.feed.scheduled': 'Scheduled',
      'creator.feed.views': 'Views',
      'creator.feed.likes': 'Likes',
      'creator.feed.comments': 'Comments',
      'creator.feed.edit': 'Edit',
      'creator.feed.delete': 'Delete',
      'creator.feed.schedule': 'Schedule',
      'creator.feed.publish': 'Publish',
      'creator.feed.noPosts': 'No posts yet',
      'creator.feed.createFirstPost': 'Create your first post to get started',
      'creator.feed.sortByDate': 'Sort by Date',
      'creator.feed.sortByViews': 'Sort by Views',
      'creator.feed.sortByLikes': 'Sort by Likes',
      'creator.feed.sortByComments': 'Sort by Comments',
      // Creator Fans
      'creator.fans.title': 'My Fans',
      'creator.fans.subtitle': 'Manage and interact with your fan community',
      'creator.fans.totalFans': 'Total Fans',
      'creator.fans.newFans': 'New Fans',
      'creator.fans.activeFans': 'Active Fans',
      'creator.fans.fanName': 'Fan Name',
      'creator.fans.joinDate': 'Join Date',
      'creator.fans.lastActive': 'Last Active',
      'creator.fans.status': 'Status',
      'creator.fans.actions': 'Actions',
      'creator.fans.message': 'Message',
      'creator.fans.block': 'Block',
      'creator.fans.unblock': 'Unblock',
      'creator.fans.active': 'Active',
      'creator.fans.inactive': 'Inactive',
      'creator.fans.blocked': 'Blocked',
      'creator.fans.premiumFans': 'Premium Fans',
      'creator.fans.totalRevenue': 'Total Revenue',
      'creator.fans.searchFans': 'Search fans...',
      'creator.fans.interactions': 'interactions',
      'creator.fans.noFansFound': 'No fans found',
      'creator.fans.tryAdjustingSearch': 'Try adjusting your search criteria',
      // Creator Marketing
      'creator.marketing.title': 'Marketing',
      'creator.marketing.subtitle': 'Promote your content and grow your audience',
      'creator.marketing.campaigns': 'Campaigns',
      'creator.marketing.promotions': 'Promotions',
      'creator.marketing.createCampaign': 'Create Campaign',
      'creator.marketing.campaignName': 'Campaign Name',
      'creator.marketing.targetAudience': 'Target Audience',
      'creator.marketing.budget': 'Budget',
      'creator.marketing.status': 'Status',
      'creator.marketing.active': 'Active',
      'creator.marketing.paused': 'Paused',
      'creator.marketing.completed': 'Completed',
      'creator.marketing.startDate': 'Start Date',
      'creator.marketing.endDate': 'End Date',
      'creator.marketing.impressions': 'Impressions',
      'creator.marketing.reach': 'Reach',
      'creator.marketing.clicks': 'Clicks',
      'creator.marketing.conversions': 'Conversions',
      'creator.marketing.promotionalPosts': 'Promotional Posts',
      'creator.marketing.promotionalPostsDesc': 'Create special promotional content for your fans',
      'creator.marketing.fanEngagementCampaigns': 'Fan Engagement Campaigns',
      'creator.marketing.fanEngagementCampaignsDesc': 'Run targeted campaigns to increase fan interaction',
      'creator.marketing.premiumContentPromotions': 'Premium Content Promotions',
      'creator.marketing.premiumContentPromotionsDesc': 'Promote your premium content to attract subscribers',
      'creator.marketing.usageThisMonth': '3/5 used this month',
      'creator.marketing.campaignsActive': '2/3 campaigns active',
      'creator.marketing.promotionsActive': '1/2 promotions active',
      'creator.marketing.useTool': 'Use Tool',
      'creator.marketing.activeCampaigns': 'Active Campaigns',
      'creator.marketing.promotionalTools': 'Promotional Tools',
      'creator.marketing.socialMediaPromotion': 'Social Media Promotion',
      'creator.marketing.socialMediaPromotionDesc': 'Share your content across social media platforms to reach more fans.',
      'creator.marketing.createPromotion': 'Create Promotion',
      'creator.marketing.specialOffers': 'Special Offers',
      'creator.marketing.specialOffersDesc': 'Create limited-time offers and discounts for your premium content.',
      'creator.marketing.createOffer': 'Create Offer',
      'creator.marketing.marketingAnalytics': 'Marketing Analytics',
      'creator.marketing.growthRate': 'Growth Rate',
      'creator.marketing.totalReach': 'Total Reach',
      'creator.marketing.newYearSpecial': 'New Year Special',
      'creator.marketing.premiumPromotion': 'Premium Promotion',
      'creator.marketing.fanAppreciationWeek': 'Fan Appreciation Week',
      'creator.marketing.engagementCampaign': 'Engagement Campaign',
      // Creator Messages
      'creator.messages.title': 'Messages',
      'creator.messages.subtitle': 'Connect with your fans directly',
      'creator.messages.inbox': 'Inbox',
      'creator.messages.sent': 'Sent',
      'creator.messages.drafts': 'Drafts',
      'creator.messages.search': 'Search messages...',
      'creator.messages.noMessages': 'No messages yet',
      'creator.messages.reply': 'Reply',
      'creator.messages.markAsRead': 'Mark as Read',
      'creator.messages.markAsUnread': 'Mark as Unread',
      'creator.messages.delete': 'Delete',
      'creator.messages.typeMessage': 'Type your message...',
      'creator.messages.send': 'Send',
      'creator.messages.searchConversations': 'Search conversations...',
      'creator.messages.online': 'Online',
      'creator.messages.offline': 'Offline',
      'creator.messages.selectConversation': 'Select a conversation',
      'creator.messages.chooseConversation': 'Choose a conversation to start messaging',
      // Creator Notifications
      'creator.notifications.title': 'Notifications',
      'creator.notifications.subtitle': 'Stay updated with your fan interactions',
      'creator.notifications.all': 'All',
      'creator.notifications.unread': 'Unread',
      'creator.notifications.read': 'Read',
      'creator.notifications.markAllRead': 'Mark all as read',
      'creator.notifications.clearAll': 'Clear all',
      'creator.notifications.noNotifications': 'No notifications',
      'creator.notifications.newFollower': 'New follower',
      'creator.notifications.newLike': 'New like',
      'creator.notifications.newComment': 'New comment',
      'creator.notifications.newMessage': 'New message',
      'creator.notifications.newTip': 'New tip',
      'creator.notifications.interactions': 'Interactions',
      'creator.notifications.earnings': 'Earnings',
      'creator.notifications.allCaughtUp': 'You\'re all caught up!',
      'creator.notifications.newSubscription': 'New Subscription',
      'creator.notifications.subscriptionMessage': 'premium_fan subscribed to your premium content',
      'creator.notifications.earningsUpdate': 'Earnings Update',
      'creator.notifications.earningsMessage': 'You earned ¥2,500 this week',
      'creator.notifications.systemUpdate': 'System Update',
      'creator.notifications.systemMessage': 'New creator tools are now available',
      // Creator Post Editor
      'creator.postEditor.title': 'Create New Post',
      'creator.postEditor.content': 'Content',
      'creator.postEditor.placeholder': 'What\'s on your mind?',
      'creator.postEditor.addImage': 'Add Image',
      'creator.postEditor.addVideo': 'Add Video',
      'creator.postEditor.visibility': 'Visibility',
      'creator.postEditor.public': 'Public',
      'creator.postEditor.private': 'Private',
      'creator.postEditor.subscribers': 'Subscribers Only',
      'creator.postEditor.schedule': 'Schedule Post',
      'creator.postEditor.publish': 'Publish',
      'creator.postEditor.saveDraft': 'Save as Draft',
      'creator.postEditor.cancel': 'Cancel',
      'creator.postEditor.subtitle': 'Share content with your fans',
      'creator.postEditor.titlePlaceholder': 'Enter post title...',
      // Creator Profile
      'creator.profile.title': 'Profile',
      'creator.profile.editProfile': 'Edit Profile',
      'creator.profile.save': 'Save',
      'creator.profile.cancel': 'Cancel',
      'creator.profile.displayName': 'Display Name',
      'creator.profile.username': 'Username',
      'creator.profile.bio': 'Bio',
      'creator.profile.website': 'Website',
      'creator.profile.location': 'Location',
      'creator.profile.category': 'Category',
      'creator.profile.description': 'Creator profile details will be displayed here',
      // Creator Queue
      'creator.queue.title': 'Content Queue',
      'creator.queue.subtitle': 'Manage your scheduled and draft posts',
      'creator.queue.scheduled': 'Scheduled',
      'creator.queue.drafts': 'Drafts',
      'creator.queue.published': 'Published',
      'creator.queue.scheduleDate': 'Schedule Date',
      'creator.queue.status': 'Status',
      'creator.queue.actions': 'Actions',
      'creator.queue.edit': 'Edit',
      'creator.queue.delete': 'Delete',
      'creator.queue.publish': 'Publish Now',
      'creator.queue.noScheduled': 'No scheduled posts',
      'creator.queue.noDrafts': 'No draft posts',
      'creator.queue.all': 'All',
      'creator.queue.scheduledFor': 'Scheduled for',
      'creator.queue.publishNow': 'Publish now',
      'creator.queue.noPostsFound': 'No posts found',
      'creator.queue.startCreatingContent': 'Start creating content to see it here',
      'creator.queue.no': 'No',
      'creator.queue.postsAvailable': 'posts available',
      'creator.queue.behindScenesPhotoShoot': 'Behind the Scenes - Photo Shoot',
      'creator.queue.weekendUpdate': 'Weekend Update',
      'creator.queue.premiumContentPreview': 'Premium Content Preview',
      'creator.queue.fanQASession': 'Fan Q&A Session',
      // Creator Statistics
      'creator.statistics.title': 'Statistics',
      'creator.statistics.subtitle': 'Track your performance and growth',
      'creator.statistics.overview': 'Overview',
      'creator.statistics.engagement': 'Engagement',
      'creator.statistics.revenue': 'Revenue',
      'creator.statistics.audience': 'Audience',
      'creator.statistics.period': 'Period',
      'creator.statistics.last7Days': 'Last 7 Days',
      'creator.statistics.last30Days': 'Last 30 Days',
      'creator.statistics.last90Days': 'Last 90 Days',
      'creator.statistics.thisYear': 'This Year',
      'creator.statistics.views': 'Views',
      'creator.statistics.likes': 'Likes',
      'creator.statistics.comments': 'Comments',
      'creator.statistics.shares': 'Shares',
      'creator.statistics.earnings': 'Earnings',
      'creator.statistics.subscribers': 'Subscribers',
      'creator.statistics.followers': 'Followers',
      'creator.statistics.engagementRate': 'Engagement Rate',
      'creator.statistics.avgViews': 'Average Views',
      'creator.statistics.avgLikes': 'Average Likes',
      'creator.statistics.topPosts': 'Top Posts',
      'creator.statistics.recentActivity': 'Recent Activity',
      'creator.statistics.averageEngagementRate': 'Average engagement rate over the last',
      // Creator Navbar
      'creator.navbar.search': 'Search...',
      'creator.navbar.notifications': 'Notifications',
      'creator.navbar.messages': 'Messages',
      'creator.navbar.profile': 'Profile',
      'creator.navbar.settings': 'Settings',
      'creator.navbar.logout': 'Logout',
      'creator.navbar.welcome': 'Welcome back',
      'creator.navbar.creator': 'Creator',
      'creator.navbar.switchToFanMode': 'Switch to Fan Mode'
    },
      ja: {
      'nav.home': 'ホーム',
      'nav.search': '検索',
      'nav.notifications': '通知',
      'nav.messages': 'メッセージ',
      'nav.profile': 'プロフィール',
      'nav.community': 'コミュニティ',
      'nav.settings': '設定',
      'nav.admin': '管理者',
      'nav.creator': 'クリエイター',
      'settings.title': '設定',
      'settings.profile': 'プロフィール',
      'settings.privacy': 'プライバシー',
      'settings.notifications': '通知設定',
      'settings.security': 'セキュリティ',
      'settings.appearance': '外観',
      'settings.language': '言語',
      'settings.help': 'ヘルプ',
      'settings.logout': 'ログアウト',
      'settings.language.title': '言語設定',
      'settings.language.description': 'サイトの表示言語を選択してください',
      'settings.language.english': 'English',
      'settings.language.japanese': '日本語',
      'settings.language.current': '現在の言語',
      'settings.language.success': '言語が正常に変更されました！',
      'settings.save': '保存',
      'settings.cancel': 'キャンセル',
      'common.loading': '読み込み中...',
      'common.success': '成功',
      'messages.languageChanged': '言語が正常に変更されました！',
      'messages.selectOption': '設定項目を選択してください',
      'dashboard.followers': 'フォロワー',
      'dashboard.following': 'フォロー中',
      'info.title': '情報',
      'info.languageChange': '言語を変更すると、サイト全体が即座に新しい言語で表示されます。',
      'admin.dashboard.title': '管理者ダッシュボード',
      'admin.dashboard.subtitle': 'プラットフォームの管理とモデレーション',
      'admin.overview': '概要',
      'admin.users': 'ユーザー管理',
      'admin.posts': '投稿管理',
      'admin.reports': '報告管理',
      'admin.totalUsers': '総ユーザー',
      'admin.totalPosts': '総投稿',
      'admin.totalReports': '報告',
      'admin.bannedUsers': '禁止ユーザー',
      'admin.removedPosts': '削除投稿',
      'admin.user': 'ユーザー',
      'admin.role': 'ロール',
      'admin.status': 'ステータス',
      'admin.joined': '登録日',
      'admin.action': 'アクション',
      'admin.ban': '禁止',
      'admin.unban': '復活',
      'admin.manager': 'マネージャー',
      'admin.creator': 'クリエイター',
      'admin.fan': 'ファン',
      'admin.active': 'アクティブ',
      'admin.banned': '禁止',
      'creator.dashboard.title': 'クリエイターダッシュボード',
      'creator.dashboard.subtitle': 'コンテンツ管理とファンとの繋がり',
      'creator.overview': '概要',
      'creator.posts': '投稿管理',
      'creator.analytics': '分析',
      'creator.fans': 'ファン管理',
      'creator.subscriptions': 'サブスクリプション',
      'creator.settings': '設定',
      'creator.settings.title': 'クリエイター設定',
      'creator.settings.subtitle': 'クリエイター体験をカスタマイズ',
      'creator.settings.contentSettings': 'コンテンツ設定',
      'creator.settings.monetization': '収益化',
      'creator.settings.profileSettings': 'プロフィール設定',
      'creator.settings.edit': '編集',
      'creator.settings.profilePicture': 'プロフィール画像',
      'creator.settings.uploadNewPicture': '新しいプロフィール画像をアップロード',
      'creator.newPost': '新しい投稿',
      'creator.followers': 'フォロワー',
      'creator.totalViews': '総視聴回数',
      'creator.totalLikes': '総いいね',
      'creator.totalEarnings': '総収益',
      'creator.postManagement': '投稿管理',
      'creator.postManagementDesc': '投稿管理機能がここに表示されます',
      'creator.analyticsDesc': '分析データがここに表示されます',
      'creator.fanManagement': 'ファン管理',
      'creator.fanManagementDesc': 'ファン管理機能がここに表示されます',
      'creator.subscriptionsDesc': 'サブスクリプション管理がここに表示されます',
      'creator.settingsDesc': '設定画面がここに表示されます',
      'creator.dashboard.newPost': '新しい投稿',
      'creator.dashboard.totalFollowers': '総フォロワー',
      'creator.dashboard.totalViews': '総視聴回数',
      'creator.dashboard.totalLikes': '総いいね',
      'creator.dashboard.totalEarnings': '総収益',
      'creator.dashboard.thisMonth': '今月',
      'creator.dashboard.quickActions': 'クイックアクション',
      'creator.dashboard.recentActivity': '最近のアクティビティ',
      'creator.dashboard.upcomingEvents': '今後のイベント',
      'creator.dashboard.performanceSummary': 'パフォーマンスサマリー',
      'creator.dashboard.viewAll': 'すべて表示',
      'creator.dashboard.viewDetailedAnalytics': '詳細分析を表示',
      'creator.dashboard.totalPosts': '総投稿数',
      'creator.dashboard.totalComments': '総コメント数',
      'creator.dashboard.engagementRate': 'エンゲージメント率',
      'creator.quickActions.myFeed': 'マイフィード',
      'creator.quickActions.myFeedDesc': 'コンテンツのパフォーマンスを管理・追跡',
      'creator.quickActions.notifications': '通知',
      'creator.quickActions.notificationsDesc': 'ファンとのやり取りを最新状態に保つ',
      'creator.quickActions.messages': 'メッセージ',
      'creator.quickActions.messagesDesc': 'ファンと直接つながる',
      'creator.quickActions.statistics': '統計',
      'creator.quickActions.statisticsDesc': 'パフォーマンスと成長を追跡',
      'creator.quickActions.myFans': 'マイファン',
      'creator.quickActions.myFansDesc': 'ファンコミュニティを管理・交流',
      'creator.quickActions.marketing': 'マーケティング',
      'creator.quickActions.marketingDesc': 'コンテンツを宣伝し、オーディエンスを拡大',
      'creator.quickActions.contentQueue': 'コンテンツキュー',
      'creator.quickActions.contentQueueDesc': 'スケジュール済みとドラフト投稿を管理',
      'creator.quickActions.settings': '設定',
      'creator.quickActions.settingsDesc': 'クリエイター体験をカスタマイズ',
      'creator.activity.newFollower': 'があなたをフォローしました',
      'creator.activity.newLikes': 'あなたの投稿に15の新しいいいね',
      'creator.activity.newComment': 'があなたの投稿にコメントしました',
      'creator.activity.newEarnings': 'チップで¥500を獲得しました',
      'creator.events.behindScenes': '舞台裏投稿',
      'creator.events.fanQA': 'ファンQ&Aセッション',
      'creator.events.premiumContent': 'プレミアムコンテンツリリース',
      'creator.events.scheduledFor': 'スケジュール済み',
      'creator.events.tomorrow': '明日',
      'creator.events.friday': '金曜日',
      'creator.events.sunday': '日曜日',
      'creator.time.hoursAgo': '時間前',
      'creator.time.daysAgo': '日前',
      // Creator Feed
      'creator.feed.title': 'マイフィード',
      'creator.feed.subtitle': 'コンテンツのパフォーマンスを管理・追跡',
      'creator.feed.createPost': '新しい投稿を作成',
      'creator.feed.allPosts': 'すべての投稿',
      'creator.feed.draft': 'ドラフト',
      'creator.feed.published': '公開済み',
      'creator.feed.scheduled': 'スケジュール済み',
      'creator.feed.views': '視聴回数',
      'creator.feed.likes': 'いいね',
      'creator.feed.comments': 'コメント',
      'creator.feed.edit': '編集',
      'creator.feed.delete': '削除',
      'creator.feed.schedule': 'スケジュール',
      'creator.feed.publish': '公開',
      'creator.feed.noPosts': 'まだ投稿がありません',
      'creator.feed.createFirstPost': '最初の投稿を作成して始めましょう',
      'creator.feed.sortByDate': '日付で並べ替え',
      'creator.feed.sortByViews': '視聴回数で並べ替え',
      'creator.feed.sortByLikes': 'いいねで並べ替え',
      'creator.feed.sortByComments': 'コメントで並べ替え',
      // Creator Fans
      'creator.fans.title': 'マイファン',
      'creator.fans.subtitle': 'ファンコミュニティを管理・交流',
      'creator.fans.totalFans': '総ファン数',
      'creator.fans.newFans': '新しいファン',
      'creator.fans.activeFans': 'アクティブファン',
      'creator.fans.fanName': 'ファン名',
      'creator.fans.joinDate': '参加日',
      'creator.fans.lastActive': '最終アクティブ',
      'creator.fans.status': 'ステータス',
      'creator.fans.actions': 'アクション',
      'creator.fans.message': 'メッセージ',
      'creator.fans.block': 'ブロック',
      'creator.fans.unblock': 'ブロック解除',
      'creator.fans.active': 'アクティブ',
      'creator.fans.inactive': '非アクティブ',
      'creator.fans.blocked': 'ブロック済み',
      'creator.fans.premiumFans': 'プレミアムファン',
      'creator.fans.totalRevenue': '総収益',
      'creator.fans.searchFans': 'ファンを検索...',
      'creator.fans.interactions': 'やり取り',
      'creator.fans.noFansFound': 'ファンが見つかりません',
      'creator.fans.tryAdjustingSearch': '検索条件を調整してみてください',
      // Creator Marketing
      'creator.marketing.title': 'マーケティング',
      'creator.marketing.subtitle': 'コンテンツを宣伝し、オーディエンスを拡大',
      'creator.marketing.campaigns': 'キャンペーン',
      'creator.marketing.promotions': 'プロモーション',
      'creator.marketing.createCampaign': 'キャンペーン作成',
      'creator.marketing.campaignName': 'キャンペーン名',
      'creator.marketing.targetAudience': 'ターゲットオーディエンス',
      'creator.marketing.budget': '予算',
      'creator.marketing.status': 'ステータス',
      'creator.marketing.active': 'アクティブ',
      'creator.marketing.paused': '一時停止',
      'creator.marketing.completed': '完了',
      'creator.marketing.startDate': '開始日',
      'creator.marketing.endDate': '終了日',
      'creator.marketing.impressions': 'インプレッション',
      'creator.marketing.reach': 'リーチ',
      'creator.marketing.clicks': 'クリック',
      'creator.marketing.conversions': 'コンバージョン',
      'creator.marketing.promotionalPosts': 'プロモーション投稿',
      'creator.marketing.promotionalPostsDesc': 'ファンのための特別なプロモーションコンテンツを作成',
      'creator.marketing.fanEngagementCampaigns': 'ファンエンゲージメントキャンペーン',
      'creator.marketing.fanEngagementCampaignsDesc': 'ファンのやり取りを増やすためのターゲットキャンペーンを実行',
      'creator.marketing.premiumContentPromotions': 'プレミアムコンテンツプロモーション',
      'creator.marketing.premiumContentPromotionsDesc': 'サブスクライバーを引き付けるためのプレミアムコンテンツを宣伝',
      'creator.marketing.usageThisMonth': '今月3/5使用済み',
      'creator.marketing.campaignsActive': '2/3キャンペーンアクティブ',
      'creator.marketing.promotionsActive': '1/2プロモーションアクティブ',
      'creator.marketing.useTool': 'ツールを使用',
      'creator.marketing.activeCampaigns': 'アクティブキャンペーン',
      'creator.marketing.promotionalTools': 'プロモーションツール',
      'creator.marketing.socialMediaPromotion': 'ソーシャルメディアプロモーション',
      'creator.marketing.socialMediaPromotionDesc': 'ソーシャルメディアプラットフォームでコンテンツを共有して、より多くのファンにリーチします。',
      'creator.marketing.createPromotion': 'プロモーション作成',
      'creator.marketing.specialOffers': '特別オファー',
      'creator.marketing.specialOffersDesc': 'プレミアムコンテンツのための期間限定オファーとディスカウントを作成します。',
      'creator.marketing.createOffer': 'オファー作成',
      'creator.marketing.marketingAnalytics': 'マーケティング分析',
      'creator.marketing.growthRate': '成長率',
      'creator.marketing.totalReach': '総リーチ',
      'creator.marketing.newYearSpecial': '新年スペシャル',
      'creator.marketing.premiumPromotion': 'プレミアムプロモーション',
      'creator.marketing.fanAppreciationWeek': 'ファン感謝週間',
      'creator.marketing.engagementCampaign': 'エンゲージメントキャンペーン',
      // Creator Messages
      'creator.messages.title': 'メッセージ',
      'creator.messages.subtitle': 'ファンと直接つながる',
      'creator.messages.inbox': '受信トレイ',
      'creator.messages.sent': '送信済み',
      'creator.messages.drafts': '下書き',
      'creator.messages.search': 'メッセージを検索...',
      'creator.messages.noMessages': 'まだメッセージがありません',
      'creator.messages.reply': '返信',
      'creator.messages.markAsRead': '既読にする',
      'creator.messages.markAsUnread': '未読にする',
      'creator.messages.delete': '削除',
      'creator.messages.typeMessage': 'メッセージを入力...',
      'creator.messages.send': '送信',
      'creator.messages.searchConversations': '会話を検索...',
      'creator.messages.online': 'オンライン',
      'creator.messages.offline': 'オフライン',
      'creator.messages.selectConversation': '会話を選択',
      'creator.messages.chooseConversation': 'メッセージを開始する会話を選択してください',
      // Creator Notifications
      'creator.notifications.title': '通知',
      'creator.notifications.subtitle': 'ファンとのやり取りを最新状態に保つ',
      'creator.notifications.all': 'すべて',
      'creator.notifications.unread': '未読',
      'creator.notifications.read': '既読',
      'creator.notifications.markAllRead': 'すべて既読にする',
      'creator.notifications.clearAll': 'すべてクリア',
      'creator.notifications.noNotifications': '通知がありません',
      'creator.notifications.newFollower': '新しいフォロワー',
      'creator.notifications.newLike': '新しいいいね',
      'creator.notifications.newComment': '新しいコメント',
      'creator.notifications.newMessage': '新しいメッセージ',
      'creator.notifications.newTip': '新しいチップ',
      'creator.notifications.interactions': 'やり取り',
      'creator.notifications.earnings': '収益',
      'creator.notifications.allCaughtUp': 'すべて最新です！',
      'creator.notifications.newSubscription': '新しいサブスクリプション',
      'creator.notifications.subscriptionMessage': 'premium_fanがあなたのプレミアムコンテンツにサブスクライブしました',
      'creator.notifications.earningsUpdate': '収益更新',
      'creator.notifications.earningsMessage': '今週¥2,500を獲得しました',
      'creator.notifications.systemUpdate': 'システム更新',
      'creator.notifications.systemMessage': '新しいクリエイターツールが利用可能になりました',
      // Creator Post Editor
      'creator.postEditor.title': '新しい投稿を作成',
      'creator.postEditor.content': 'コンテンツ',
      'creator.postEditor.placeholder': '何を考えていますか？',
      'creator.postEditor.addImage': '画像を追加',
      'creator.postEditor.addVideo': '動画を追加',
      'creator.postEditor.visibility': '公開設定',
      'creator.postEditor.public': '公開',
      'creator.postEditor.private': '非公開',
      'creator.postEditor.subscribers': 'サブスクライバーのみ',
      'creator.postEditor.schedule': '投稿をスケジュール',
      'creator.postEditor.publish': '公開',
      'creator.postEditor.saveDraft': '下書きとして保存',
      'creator.postEditor.cancel': 'キャンセル',
      'creator.postEditor.subtitle': 'ファンとコンテンツを共有',
      'creator.postEditor.titlePlaceholder': '投稿タイトルを入力...',
      // Creator Profile
      'creator.profile.title': 'プロフィール',
      'creator.profile.editProfile': 'プロフィール編集',
      'creator.profile.save': '保存',
      'creator.profile.cancel': 'キャンセル',
      'creator.profile.displayName': '表示名',
      'creator.profile.username': 'ユーザー名',
      'creator.profile.bio': '自己紹介',
      'creator.profile.website': 'ウェブサイト',
      'creator.profile.location': '場所',
      'creator.profile.category': 'カテゴリ',
      'creator.profile.description': 'クリエイタープロフィールの詳細がここに表示されます',
      // Creator Queue
      'creator.queue.title': 'コンテンツキュー',
      'creator.queue.subtitle': 'スケジュール済みとドラフト投稿を管理',
      'creator.queue.scheduled': 'スケジュール済み',
      'creator.queue.drafts': '下書き',
      'creator.queue.published': '公開済み',
      'creator.queue.scheduleDate': 'スケジュール日',
      'creator.queue.status': 'ステータス',
      'creator.queue.actions': 'アクション',
      'creator.queue.edit': '編集',
      'creator.queue.delete': '削除',
      'creator.queue.publish': '今すぐ公開',
      'creator.queue.noScheduled': 'スケジュール済みの投稿がありません',
      'creator.queue.noDrafts': '下書きの投稿がありません',
      'creator.queue.all': 'すべて',
      'creator.queue.scheduledFor': 'スケジュール済み',
      'creator.queue.publishNow': '今すぐ公開',
      'creator.queue.noPostsFound': '投稿が見つかりません',
      'creator.queue.startCreatingContent': 'コンテンツを作成してここに表示してください',
      'creator.queue.no': 'なし',
      'creator.queue.postsAvailable': '投稿利用可能',
      'creator.queue.behindScenesPhotoShoot': '舞台裏 - 写真撮影',
      'creator.queue.weekendUpdate': '週末アップデート',
      'creator.queue.premiumContentPreview': 'プレミアムコンテンツプレビュー',
      'creator.queue.fanQASession': 'ファンQ&Aセッション',
      // Creator Statistics
      'creator.statistics.title': '統計',
      'creator.statistics.subtitle': 'パフォーマンスと成長を追跡',
      'creator.statistics.overview': '概要',
      'creator.statistics.engagement': 'エンゲージメント',
      'creator.statistics.revenue': '収益',
      'creator.statistics.audience': 'オーディエンス',
      'creator.statistics.period': '期間',
      'creator.statistics.last7Days': '過去7日間',
      'creator.statistics.last30Days': '過去30日間',
      'creator.statistics.last90Days': '過去90日間',
      'creator.statistics.thisYear': '今年',
      'creator.statistics.views': '視聴回数',
      'creator.statistics.likes': 'いいね',
      'creator.statistics.comments': 'コメント',
      'creator.statistics.shares': 'シェア',
      'creator.statistics.earnings': '収益',
      'creator.statistics.subscribers': 'サブスクライバー',
      'creator.statistics.followers': 'フォロワー',
      'creator.statistics.engagementRate': 'エンゲージメント率',
      'creator.statistics.avgViews': '平均視聴回数',
      'creator.statistics.avgLikes': '平均いいね',
      'creator.statistics.topPosts': '人気投稿',
      'creator.statistics.recentActivity': '最近のアクティビティ',
      'creator.statistics.averageEngagementRate': '過去の平均エンゲージメント率',
      // Creator Navbar
      'creator.navbar.search': '検索...',
      'creator.navbar.notifications': '通知',
      'creator.navbar.messages': 'メッセージ',
      'creator.navbar.profile': 'プロフィール',
      'creator.navbar.settings': '設定',
      'creator.navbar.logout': 'ログアウト',
      'creator.navbar.welcome': 'おかえりなさい',
      'creator.navbar.creator': 'クリエイター',
      'creator.navbar.switchToFanMode': 'ファンモードに切り替え'
    }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('myfans_language');
    return (saved as Language) || 'ja';
  });

  const setLanguage = (lang: Language) => {
    if (lang !== language) {
      setLanguageState(lang);
      localStorage.setItem('myfans_language', lang);
      // Force a re-render by updating the state
      // The page will automatically update without reload
    }
  };

  const t = (key: string): string => {
    const result = (translations[language] as Record<string, string>)[key] || key;
    // Debug logging
    if (language === 'ja' && key.startsWith('creator.')) {
      console.log(`JP Translation for "${key}":`, result);
    }
    return result;
  };

  useEffect(() => {
    document.documentElement.lang = language;
    console.log('Language changed to:', language);
  }, [language]);

  const value: LanguageContextType = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
